version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn run lint
  build:
    docker:
      - image: circleci/node:7.10

    steps:
      - checkout

      - run:
          name: install dependencies
          command: 'yarn'
      - run:
          name: build module
          command: yarn run build
      - run:
          name: deploy to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - master
